/**
 * BusinessParser: High-Accuracy Hinglish Engine for Vani.
 * Optimized for Samosa, Chai and common Hindi expense phrases.
 */

// 1. Smart Costing Rules (Base Percentages)
const COST_RULES = {
  SAMOSA: { base: 0.25, bulk: 0.18, threshold: 50 },
  CHAI: { base: 0.20, bulk: 0.15, threshold: 50 },
  "VADA PAV": { base: 0.30, bulk: 0.22, threshold: 50 },
  DEFAULT: { base: 0.20, bulk: 0.15, threshold: 100 }
};

/**
 * Calculates Automatic Raw Material Cost
 */
export const calculateRawMaterialCost = (itemName, quantity, amount) => {
  const name = itemName.toUpperCase();
  const rule = COST_RULES[name] || COST_RULES.DEFAULT;
  
  const percentage = (quantity >= rule.threshold) ? rule.bulk : rule.base;
  const cost = Math.floor(amount * percentage);
  
  return {
    item: `RAW MATERIAL (${name})`,
    quantity: 1,
    amount: cost,
    type: 'expense',
    isAutoGenerated: true
  };
};

export const extractBusinessData = (text) => {
  // 1. Expanded Pre-processing & Hinglish Number Normalization
  let processed = text.toLowerCase()
    // Numbers
    .replace(/\bhundred\b|\bsau\b/g, ' 100 ')
    .replace(/\bthousand\b|\bhazar\b/g, ' 1000 ')
    .replace(/\blakh\b/g, ' 100000 ')
    .replace(/\bpachas\b/g, ' 50 ')
    .replace(/\bbc\b|\bbees\b/g, ' 20 ')
    .replace(/\bdas\b/g, ' 10 ')
    .replace(/\bpandra\b/g, ' 15 ')
    .replace(/\btees\b/g, ' 30 ')
    .replace(/\bchalis\b/g, ' 40 ')
    .replace(/\bek\b/g, ' 1 ')
    .replace(/\bdo\b/g, ' 2 ')
    // Common plural/aliasing
    .replace(/\bsamosae|\bsamosay\b/g, 'samosa')
    .replace(/\bchaiya\b/g, 'chai')
    .replace(/\brupaye|\brupayeb\b|\brs\b|\brupees\b/g, 'rupee');

  const normalized = processed.normalize('NFD').replace(/[\u0300-\u036f]/g, "");

  // Keyword Dictionaries for Context
  const expenseWords = ['spent', 'kharcha', 'diye', 'paid', 'loss', 'nuksan', 'laga', 'invested', 'repair', 'purchase', 'bill', 'payment', 'liye', 'kharida', 'khareeda'];
  const saleWords = ['sold', 'becha', 'sale', 'got', 'income', 'order', 'kamaya', 'collection', 'profit', 'daily', 'mile', 'aaye'];

  // Entity Definitions
  const knownItems = ['samosa', 'chai', 'milk', 'sugar', 'vada pav', 'bread', 'oil', 'gas', 'ingredients', 'water', 'tea', 'aloo', 'maida'];

  const results = {
    items: [],
    expenses: [],
    totalEarnings: 0,
    totalExpenses: 0,
    rawText: text,
    timestamp: new Date().toISOString()
  };

  const numberMatches = [...normalized.matchAll(/(\d+)/g)];
  if (numberMatches.length === 0) return results;

  // PASS 1: Structured Item + Amount extraction
  // Logic: "20 SAMOSA 200 RUPEE" or "SAMOSA 200 RUPEE"
  knownItems.forEach(kItem => {
    const escaped = kItem.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Pattern: ([quantity]?) [item] ([amount]?) 
    const itemRegex = new RegExp(`(?:(\\d+)\\s+)?(${escaped})(?:\\s+\\w+)?\\s+(\\d+)`, 'gi');
    
    let m;
    while ((m = itemRegex.exec(normalized)) !== null) {
      const qty = parseInt(m[1] || 1);
      const amt = parseInt(m[3]);
      
      const isExpense = expenseWords.some(w => normalized.includes(w)) || normalized.includes('ke liye');
      
      if (isExpense) {
        results.expenses.push({ item: kItem.toUpperCase(), quantity: qty, amount: amt, type: 'expense' });
        results.totalExpenses += amt;
      } else {
        results.items.push({ item: kItem.toUpperCase(), quantity: qty, amount: amt, type: 'sale' });
        results.totalEarnings += amt;
      }
    }
  });

  // PASS 2: If no structured items found, but numbers exist
  if (results.totalEarnings === 0 && results.totalExpenses === 0) {
    const total = numberMatches.reduce((sum, n) => sum + parseInt(n[0]), 0);
    const isExpense = expenseWords.some(w => normalized.includes(w)) || normalized.includes('ke liye');
    const isSale = saleWords.some(w => normalized.includes(w));
    
    if (isExpense) {
      results.totalExpenses = total;
      results.expenses.push({ item: 'EXPENSE', quantity: 1, amount: total, type: 'expense' });
    } else if (isSale || total > 0) {
      results.totalEarnings = total;
      results.items.push({ item: 'GENERAL SALE', quantity: 1, amount: total, type: 'sale' });
    }
  }

  return results;
};

export const getStockSuggestions = (history) => {
    return {
        tip: "Stock up on Samosas! Weekends usually see a 30% jump in snack orders.",
        action: "Recommended: Buy 100 extra Samosas"
    };
};
